var positions = {
    "QB": "Quarterback",
    "RB": "Running Back",
    "FB": "Fullback",
    "WR": "Wide Receiver",
    "TE": "Tight End",
    "OL": "Offensive Lineman",
    "OG": "Offensive Guard",
    "C": "Center",
    "G": "Guard",
    "LG": "Left Guard",
    "RG": "Right Guard",
    "T": "Tackle",
    "LT": "Left Tackle",
    "RT": "Right Tackle",
    "K": "Kicker",
    "KR": "Kick Returner",
    "DL": "Defensive Lineman",
    "DE": "Defensive End",
    "DT": "Defensive Tackle",
    "OT": "Offensive Tackle",
    "NT": "Nose Tackle",
    "LB": "Linebacker",
    "ILB": "Inside Linebacker",
    "OLB": "Outside Linebacker",
    "MLB": "Middle Linebacker",
    "DB": "Defensive Back",
    "CB": "Cornerback",
    "FS": "Free Safety",
    "SS": "Strong Safety",
    "S": "Safety",
    "P": "Punter",
    "PR": "Punt Returner"
}

module.exports = positions;