var teams = {
    "ARI": "Arizona Cardinals",
    "ATL": "Atlanta Falcons",
    "BAC": "Baltimore Colts",
    "BAL": "Baltimore Ravens",
    "BOB": "Boston Braves",
    "BOR": "Boston Redskins",
    "BOS": "Boston Patriots",
    "BUF": "Buffalo Bills",
    "CAR": "Carolina Panthers",
    "CHC": "Chicago Cardinals",
    "CHI": "Chicago Bears",
    "CHS": "Chicago Staleys",
    "CIN": "Cincinnati Bengals",
    "CLE": "Cleveland Browns",
    "CLR": "Cleveland Rams",
    "DAL": "Dallas Cowboys",
    "DAT": "Dallas Texans",
    "DEC": "Decatur Staleys",
    "DEN": "Denver Broncos",
    "DET": "Detroit Lions",
    "GBY": "Green Bay Packers",
    "HOO": "Houston Oilers",
    "HOU": "Houston Texans",
    "IND": "Indianapolis Colts",
    "JAC": "Jacksonville Jaguars",
    "KC": "Kansas City Chiefs",
    "LAC": "Los Angeles Chargers",
    "LAI": "Los Angeles Raiders",
    "LAM": "Los Angeles Rams",
    "MIA": "Miami Dolphins",
    "MIN": "Minnesota Vikings",
    "NWE": "New England Patriots",
    "NOR": "New Orleans Saints",
    "NYG": "New York Giants",
    "NYJ": "New York Jets",
    "NYT": "New York Titans",
    "OAK": "Oakland Raiders",
    "PHI": "Philadelphia Eagles",
    "PHX": "Phoenix Cardinals",
    "PIP": "Pittsburgh Pirates",
    "PIT": "Pittsburgh Steelers",
    "POR": "Portsmouth Spartans",
    "SD": "San Diego Chargers",
    "SEA": "Seattle Seahawks",
    "SF": "San Francisco 49ers",
    "SLC": "Saint Louis Cardinals",
    "STL": "Saint Louis Rams",
    "TB": "Tampa Bay Buccaneers",
    "TEN": "Tennessee Titans",
    "TNO": "Tennessee Oilers",
    "WAS": "Washington Redskins",
}

module.exports = teams;